include $(THEOS)/makefiles/common.mk
BUNDLE_NAME = ClipboardPreferences
ClipboardPreferences_FILES = RootController.m
ClipboardPreferences_CFLAGS = -fobjc-arc
ClipboardPreferences_FRAMEWORKS = UIKit
ClipboardPreferences_PRIVATE_FRAMEWORKS = Preferences
ClipboardPreferences_LIBRARIES = roothide
ClipboardPreferences_INSTALL_PATH = /Library/PreferenceBundles
include $(THEOS_MAKE_PATH)/bundle.mk
